server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue

taco:
  orders:
    pageSize: 10

  discount:
    codes:
      abcdef: 10

logging:
  level:
    tacos: DEBUG

---
spring:
  profiles: prod

logging:
  level:
    tacos: WARN