server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    host: localhost
    port: 61616
    user: tacosweb
    password: letm3in
    embedded:
      enabled: false

taco:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10

logging:
  level:
    tacos: DEBUG

---
spring:
  profiles: jms-template, jms-listener
  # The values given here are actually the default values. But they are explicitly
  # set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

---
spring:
  profiles: kafka-listener

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos

---
spring:
  profiles: prod

  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n

logging:
  level:
    tacos: WARN

